// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfFBvmJecabJ-5py6rR1aAr-vuayYcHBc',
    appId: '1:242101044487:web:471e5299c56ff3f50bb1a2',
    messagingSenderId: '242101044487',
    projectId: 'lms-tiofan',
    authDomain: 'lms-tiofan.firebaseapp.com',
    storageBucket: 'lms-tiofan.firebasestorage.app',
    measurementId: 'G-KS8P2DD4F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOIdUQFpxHjJgCMxl9eWQ7lm5nZaPuF8',
    appId: '1:242101044487:android:ce9bb1af5d65f5ae0bb1a2',
    messagingSenderId: '242101044487',
    projectId: 'lms-tiofan',
    storageBucket: 'lms-tiofan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCHlWHlyNisXcVJDSVUAnTZ-VsMXMq2y8',
    appId: '1:242101044487:ios:1ac8fa597412b8fe0bb1a2',
    messagingSenderId: '242101044487',
    projectId: 'lms-tiofan',
    storageBucket: 'lms-tiofan.firebasestorage.app',
    iosBundleId: 'com.example.app46',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCHlWHlyNisXcVJDSVUAnTZ-VsMXMq2y8',
    appId: '1:242101044487:ios:1ac8fa597412b8fe0bb1a2',
    messagingSenderId: '242101044487',
    projectId: 'lms-tiofan',
    storageBucket: 'lms-tiofan.firebasestorage.app',
    iosBundleId: 'com.example.app46',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfFBvmJecabJ-5py6rR1aAr-vuayYcHBc',
    appId: '1:242101044487:web:f0c559e6d65435d40bb1a2',
    messagingSenderId: '242101044487',
    projectId: 'lms-tiofan',
    authDomain: 'lms-tiofan.firebaseapp.com',
    storageBucket: 'lms-tiofan.firebasestorage.app',
    measurementId: 'G-EYJK39XLGY',
  );
}
